### ISSUE TITLE
sops truncates the file to zero after a failed key rotation

### ISSUE THREAD

**Issue by cohadar** [getsops/sops#855] opened 2021-04-15 09:47 UTC
Sops version: 3.7.1 (Installed from deb package)

How to reproduce:
1. create example.yaml using one KMS and one PGP key
2. turn off your aws profile / credentials
3. try to rotate the file in place: `sops -r -i example.yaml`

What happens:
1. example.yaml file gets truncated to zero bytes!
2. sops prints no error messages
3. sops returns exit code zero as if everything was ok

What I would like to happen:
1. sops detects that not all master keys are available
2. sops prints error message: you cannot rotate because you are missing key X
3. sops exits with non-zero code.

**Comment by cohadar** [comment] 2021-04-15 09:51
4. sops should not delete data in my files when error happens during rotation

**Comment by james-callahan** [comment] 2023-10-04 18:42
This is still an issue with sops 3.8.0

**Comment by felixfontein** [comment] 2023-10-07 21:03
Simple reproducer:
1. Check out sops repository.
2. Run `sops -r -i stores/ini/test_resources/example.json` in it.

The cause is that the error handling in https://github.com/getsops/sops/blob/main/cmd/sops/main.go#L713-L969 is pretty much messed up. The correct error is put into `err` here: https://github.com/getsops/sops/blob/main/cmd/sops/main.go#L897 - but that `err` is apparently a **different** `err` than the one that is checked here: https://github.com/getsops/sops/blob/main/cmd/sops/main.go#L967 (that one is still `nil`).

From how I understand Go the assignment in https://github.com/getsops/sops/blob/main/cmd/sops/main.go#L843 creates a new `err` in the local scope which shadows the `err` from the outer scope. Since this happens pretty extensively in the function, my bet is that there are several similar bugs in there.

I'm somewhat surprised that `make staticcheck` isn't flagging this, as obviously `err` **is** ignored here.

**Comment by felixfontein** [comment] 2023-10-08 13:27
When removing `bin/staticcheck` and re-running `make staticcheck` it now found the problem. I guess I had an older version installed...

**Comment by felixfontein** [comment] 2023-10-08 13:31
Fixed by #1317.

**Closed** 2023-10-09 06:54 UTC
