### ISSUE TITLE
using flag `--set` on new root level key, creates a new file with just the added key

### ISSUE THREAD

**Issue by mattgstevens** [getsops/sops#407] opened 2018-12-12 10:47 UTC
### Version
sops 3.1.1

### Bug behaviour
When using `sops --set '["some-key"]["nested-key"] "some-value" secrets.yml'` where `some-key` does not exist at the root level of `secrets.yml` and the file is rewritten with only the keys in the command.

### Expected behaviour
The new key is added to the top level, with the nested key(s) and the existing keys in the file.

### Discussion
It seems this is the intended behaviour based on https://github.com/mozilla/sops/issues/336. The difference is that `nested-key` causes the bug.

**Comment by autrilla** [comment] 2018-12-13 22:33
This is most certainly not intended, and what you describe as the expected behavior is what should happen. Marked as a bug, thanks for the report!

**Comment by scalen** [comment] 2021-09-16 20:40
The PR linked to this issue looks like a good fix, and this bug is causing some serious pain (at least for me!). Is there an average time that a PR can be expected to take to get through review?

It would be a shame to have to look for a workaround of my own if this isn't likely to be released any time soon 🙁

**Comment by krzema12** [comment] 2022-01-13 19:15
I've found a workaround: first set the top-level key to any string value (not object), and then proceed with setting your nested value(s):

```
sops --set '["some-key"] "irrelevant-value-it-will-be-overridden-with-the-below-command"' secrets.yml
sops --set '["some-key"]["nested-key"] "some-value"' secrets.yml
```

**Comment by jimmythedog** [comment] 2022-06-30 09:48
#899 also works for me (found this issue after searching when `--set` deleted everything from a file!)

I can see that it's slated for [v3.8.0](https://github.com/mozilla/sops/milestone/4), but that has no date - do we have a rough idea of when this fix will be released please?

**Closed** 2023-08-15 22:51 UTC
Labels: bug, help wanted

**Comment by jimmythedog** [comment] 2023-08-16 03:57
Still no release date for `v3.8.0` (as that is the milestone for #899)?
