### ISSUE TITLE
Main project page getsops/sops never loads because of README rendering issue

### ISSUE THREAD

**Issue by 0anton** [getsops/sops#1455] opened 2024-03-08 15:06 UTC
The main project page https://github.com/getsops/sops is not accessible README page rendering fails. The timeout is up to 1 minute, getting the filling that the complete GitHub is down.

**Repro**

Open the https://github.com/getsops/sops/ page or navigate from any other tab (Issues, Actions) to the Code Tab.
The page will hang.

**Expected**

The page loads quickly, in less then 1 second.

**Discussion**

It is probably the length and the complexity of the README, which causes the GitHub renderer to fail.
Splitting it into smaller parts to navigating users to the site (page.github.com) with the documentation will help.

![image](https://github.com/getsops/sops/assets/17309924/e14d1860-58e8-45e7-9cf1-645cca666a5f)

**Comment by felixfontein** [comment] 2024-03-09 09:22
Duplicate of #1411.

**Comment by RossComputerGuy** [comment] 2024-03-21 04:17
I'm having the same issue, it's loaded a few times for me but fails most of the time.

**Comment by felixfontein** [comment] 2024-03-24 15:10
Closing as this is now mostly fixed and this is a duplicate of #1411.

**Closed by felixfontein** 2024-03-24 15:10 UTC
