### ISSUE TITLE
SOPS displacing comments and causing YAML-breaking invalid syntax error and data loss

### ISSUE THREAD

**Issue by lucabello** [getsops/sops#1068] opened 2022-05-31 14:45 UTC
Hello everyone; I found a bug in the SOPS encryption, which you can replicate yourself.

Unencrypted file `test.yaml`:
```yaml
this:
  is:
    an: example
  # comment
```

I use age encryption, so I set up the SOPS_AGE_RECIPIENTS and SOPS_AGE_KEY_FILE variables, and then run `sops --encrypt --encrypted-regex an test.yaml`, obtaining this:

```yaml
this:
    is:
        an: ENC[AES256_GCM,data:7ew99FdoYQ==,iv:62k8jSLjg2l7YyorqOf9bobpgT7m+1qeEK66JpyObTE=,tag:caRiamKAO9TqZHj2qfKAgA==,type:str]
sops:
# comment
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age107p580kfl3mlr2x7jqfhattzv0a3kd88ugjq2p5tsjz59jzdmdfsj2qwm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa3VuTFBucnV4QldrZW0z
            am9jTkw1ejZIUjBUVHpRTjRONUNTYnRXWFVRCncwdk5adnpDZktnK3JwVWU0R1o4
            UGlIOHpSdUpTQjBhWnMwcXAyZlhmTFEKLS0tIFk2bitXOHN2T2VIbHZzVnVlTVpn
            VGNUSkdFWENLSEFQdGh4OW1TMk1HZHMKvMCQo5SXkMk9HQ4Bv7n1UFj+IZDi0z8K
            1LJKCovXp7d+zceCwbVM9zfbleF7AvFuyWSbw7o11WpE4vtaD8fDWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-31T14:38:08Z"
    mac: ENC[AES256_GCM,data:BNPYx43KNPdggGC/+qgHQfoMj+ctnrwjOpt+pOzoWcQCcS3IP1h0FtD/UcSc8mLTxS2+6gBBiFU8JIdnr8XwueIeGbcx0zEk8LZdspv0DuVQoC5AbiU4qnvCFRY7MIdmSKacG7zXVN4nQ2kW/Ip7jqhBAqZJl5cbUBcaQOgfGCo=,iv:aLQ+lhmgxzyrQphjknd1O1KHC6BVG1E0hM9tCfFs+J4=,tag:sHhaEqLU+/VRDRjTajAnwQ==,type:str]
    pgp: []
    encrypted_regex: an
    version: 3.7.3
```

As you can see, the `# comment` line is moved inside the sops metadata; whenever that file is decrypted, the comment will be gone (hence the data loss I mention in the title).

The reason why this is important is because my team is using some comment "tags" to mark code blocks, and the last tag disappears after encrypting-and-decrypting a file.

I did some extra testing to try to understand when this was happening, and I gathered some conclusions: it only happens if the indentation is **at least** the one in my example file (so at least 3) and the if the comment is "less indented" than the last line.

Sorry if this is a known issue and I missed it! :)

**Comment by felixfontein** [comment] 2022-05-31 17:37
Thanks for this report! I can confirm that this happens with the latest version.

**Comment by felixfontein** [comment] 2022-05-31 17:42
Interestingly I cannot reproduce this when removing the empty line after the comment... Then in both cases it works fine. But if there is an empty line after the comment, the error happens.

**Comment by lucabello** [comment] 2022-06-01 07:13
I also noticed it can displace multiple comments into the sops metadata, as long as they are in consecutive lines after the `# comment` in my example and they are "indented enough"

But anyway, thanks for addressing it quickly! Hope it gets reviewed and merged soon :)

**Comment by BlackBsd** [comment] 2022-09-14 20:36
Just wanted to add to this issue, as i think it might be the same problem.  There is a helm chart values.yaml file for the kube-prometheus-stack located at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml that also causes invalid syntax when you try to encrypt and decrypt the file.

**Comment by felixfontein** [comment] 2022-09-15 19:15
@BlackBsd indeed, there are more such bugs. A minimal reproducer for the issue you reported is
```.yaml
a:
  b:
    c:
      d: ""
    # e

# f
g: {}
```

> It also seems like the output of the encryption removes all blank lines that might have been present in the original file.
> 
> In addition, some of the indention is also getting changed.  For example the first entry, "defaultRules:"

These are both normal and to be expected. Sops should produce semantically equivalent YAML files (including comments), not the original YAML file back.

**Comment by felixfontein** [comment] 2022-09-18 13:50
Meh. Now I tried to spend quite some time to figure out why this is still not fixed, only to realize that the fix merged (#1069) works fine, but hasn't been released yet.

So well, this is already fixed on the develop branch since beginning of June...

**Comment by BlackBsd** [comment] 2022-09-19 14:51
That is awesome, thank you.  When do you foresee this making it into a new release?

**Comment by strowi** [comment] 2022-11-04 16:07
any update on this?

**Comment by felixfontein** [comment] 2022-11-27 20:47
There has not been a new release, so: no. Unfortunately not. :(

**Closed** 2023-08-24 16:11 UTC

**Comment by digitalstudium** [comment] 2024-02-29 14:10
In version 3.8.1 It is still displacing comments in YAML
