### ISSUE TITLE
Unable to see README

### ISSUE THREAD

**Issue by ikarlashov** [getsops/sops#1419] opened 2024-01-24 07:57 UTC
Today I visited sops repo and saw this:

<img width="833" alt="image" src="https://github.com/getsops/sops/assets/23174935/c94cffd8-d33c-4fc6-a159-26a2f29722b0">

Perhaps, it's a time to split README into pieces :)

**Comment by felixfontein** [comment] 2024-01-24 18:57
Duplicate of #1411.

**Closed** 2024-01-28 08:02 UTC
