### ISSUE TITLE
Consider having `--set` render error for invalid JSON value 

### ISSUE THREAD

**Issue by camlow325** [getsops/sops#1138] opened 2022-11-01 17:21 UTC
When the [--set](https://github.com/mozilla/sops#46set-a-sub-part-in-a-document-tree) option is used to set a value into an encrypted file but the specified value is not valid JSON, `sops` returns a `0` exit code but sets a `null` value into the file:

```
$ sops --set '["test"] bogus' test.yaml

$ sops -d test.yaml
test: null
```

It seems misleading for the `sops` command to succeed for an invalid value. A better response may be for the `sops` command to return a non-zero exit code and not update the encrypted file with the bad setting value.

**Comment by duthils** [comment] 2024-03-31 12:15
I can't reproduce this behavior on the `main` branch, I get:
```
$ sops --set '["test"] bogus' test.json
Value for --set is not valid JSON
exit status 7
```

**Comment by felixfontein** [comment] 2024-03-31 13:38
I think this was fixed by https://github.com/getsops/sops/pull/1311/files#diff-774985986bb4d9a68a16d022fd494dfec2de4d2e21bfd35a450cb2839c7438b2.

**Comment by duthils** [comment] 2024-03-31 13:46
This issue can be closed, then.

**Closed** 2024-03-31 14:00 UTC
